### PR TITLE
Add section about Corfucoin

### PR DESCRIPTION
**Pull request by musalbas**

### CODE REVIEW

**Comment by musalbas** [comment]
This adds a section about Corfucoin to the website, an altcoin for the summer school we've developed.

Adding an extra menu button causes the menu to extend past the pink bit. I tried resizing the menu box so that this doesn't happen, but that causes the background image to repeat so it looks more visually displeasing.

**Comment by dionyziz** [comment]
Just merged you, it's looking good here. Can you upload a screenshot with the issue?

**Comment by musalbas** [comment]
Thanks.

Here's what it looks like on Chromium:
image

Perhaps this is the expected behaviour - looks fine either way.

**Comment by dionyziz** [comment]
Looks alright

**Pull request merged**
